name: project deploy
on: 
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: run ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 114
          script:
            rm -rf  ./CICD-practice
            git clone https://github.com/gaangstar/CICD-practice.git
            cd ./CICD-practice
            chmod 755 ./gradlew
            ./gradlew bootJar
            docker rm -f back
            docker image prune -f
            docker build --tag gaangstar/back:latest .
            docker run -d --name back -p 8080:8080 gaangstar/back:latest